### ISSUE TITLE
Hello author, when will the code be released

### ISSUE THREAD

**Issue by piantou** [passerer/SRLane#1]
Hello author, **when** will the code be released？

**Comment by passerer** [comment]
Hello. We would send you with a copy right away if you could kindly provide email address.

**Comment by piantou** [comment]
my email is wei1872625667@163.com，thank you very much.

**Comment by smilecode-github** [comment]
I want to receive it too.
My email is woals2274@naver.com
Thank you!

**Comment by BaeSungHyun** [comment]
Hi can I receive copy too? Also thanks for great research.
My email is shijr0725@gmail.com

**Comment by MrL-CV** [comment]
Your attention to detail and innovative approach resulted in a truly commendable outcome!
I want to receive it too.
My email is 2301594686@qq.com
Thank you very much !!!

**Comment by XXXVincent** [comment]
Nice work! Could you send a copy to vincent_xwh@hotmail.com
Many thanks!

**Comment by ycdhqzhiai** [comment]
@passerer  Can you send a copy to my email ycdhqzhiai@163.com? Thank you very much

**Comment by Minnchong** [comment]
Could you send a copy to 908514741@qq.com？Thank you. @passerer

**Comment by guohao02** [comment]
Could you send a copy to 2498670446@qq.com ?
Thank you. @passerer

**Comment by Minnchong** [comment]
Could you send a copy to 908514741@qq.com ？Thank you. @passerer

**Comment by passerer** [comment]
> Could you send a copy to [908514741@qq.com](mailto:908514741@qq.com) ？Thank you. @passerer

Hello, I have already sent it on February 22nd. Please check your spam box.
