### ISSUE TITLE
complete the code repository

### ISSUE THREAD

**Issue by yueyunqingwu** [passerer/SRLane#2]
Since the author has submitted the paper to arxiv and claimed the code is opened, please complete the code repository. Thanks!

**Comment by passerer** [comment]
The code will be uploaded after my vacation. If the code and pre-trained weights are in need right away, please refer to this [https://github.com/passerer/SRLane/issues/1#issuecomment-1918314837](issue) .

**Comment by passerer** [comment]
The code will be uploaded after my vacation. If the code and pre-trained weights are in need right away, please refer to this [issue](https://github.com/passerer/SRLane/issues/1#issuecomment-1918314837)
