### ISSUE TITLE
弯道效果

### ISSUE THREAD

**Issue by ycdhqzhiai** [passerer/SRLane#3]
在弯道上的表现好像很差

**Comment by passerer** [comment]
指标能复现吗

**Comment by passerer** [comment]
请把问题描述得更清晰一点，例如指标等

**Comment by ycdhqzhiai** [comment]
没，我比较关注实车效果，用自己一小部分数据集训练了下，然后可视化看了下效果。跑了下culane validate，效果还是很好的，感谢作者开源

**Comment by passerer** [comment]
不同数据集的数据分布不一样，config还是要作对应的修改
