### ISSUE TITLE
TuSimple 

### ISSUE THREAD

**Issue by DaDaDalong** [passerer/SRLane#5]
Hello, is there no information about training code and data processing on TuSimple dataset?

**Comment by passerer** [comment]
TuSimple dataset is outdated and its performance has plateaued, so we generally advise against using it for new experiments. If you insist on working with it, we can prepare a dedicated branch with the config and data processing code.

**Comment by DaDaDalong** [comment]
Yes, I may still need to use the Tusimple dataset, can you provide it? Special thanks!

**Comment by passerer** [comment]
See 'tusimple' branch
