### ISSUE TITLE
如何推理单张图片

### ISSUE THREAD

**Issue by Minnchong** [passerer/SRLane#8]
请问如何利用代码推理单张图片

**Comment by passerer** [comment]
目前没有提供直接针对单张图片进行推理的接口。不过，可以通过将单张图片添加到一个验证集中，然后使用 `CUDA_VISIBLE_DEVICES=0 python tools/main.py configs/exp_srlane_culane.py --load_from checkpoint/baseline.pth --validate`来推理这个验证集
